import type { StudyWeek } from "@/lib/domain/types";

export const SEED_WEEKS: StudyWeek[] = [
  {
    id: "week-1",
    weekNumber: 1,
    theme: "基礎データ構造 + 配列/ハッシュ",
    pythonTopics: ["list", "dict", "set"],
    leetcodeTopics: ["ArrayHashing"],
    sqlTopics: ["SelectWhere"],
    englishFocus: "brute force説明",
    problemSlugs: [
      "two-sum",
      "contains-duplicate",
      "valid-anagram",
      "group-anagrams",
      "top-k-frequent-elements",
    ],
    sqlSlugs: [
      "recyclable-and-low-fat-products",
      "find-customer-referee",
      "big-countries",
    ],
    pythonConceptSlugs: ["list", "dict", "set"],
  },
  {
    id: "week-2",
    weekNumber: 2,
    theme: "Two Pointers + JOIN",
    pythonTopics: ["enumerate", "sort", "Counter"],
    leetcodeTopics: ["TwoPointers"],
    sqlTopics: ["Join"],
    englishFocus: "complexity説明",
    problemSlugs: [
      "valid-palindrome",
      "two-sum-ii",
      "3sum",
      "container-with-most-water",
    ],
    sqlSlugs: [
      "article-views-i",
      "invalid-tweets",
      "replace-employee-id-with-the-unique-identifier",
    ],
    pythonConceptSlugs: ["sort-sorted", "counter"],
  },
  {
    id: "week-3",
    weekNumber: 3,
    theme: "Sliding Window + GROUP BY",
    pythonTopics: ["defaultdict", "sliding window実装"],
    leetcodeTopics: ["SlidingWindow"],
    sqlTopics: ["GroupByHaving"],
    englishFocus: "optimization説明",
    problemSlugs: [
      "best-time-to-buy-and-sell-stock",
      "longest-substring-without-repeating-characters",
      "longest-repeating-character-replacement",
      "minimum-window-substring",
    ],
    sqlSlugs: [
      "product-sales-analysis-i",
      "customer-who-visited-but-did-not-make-any-transactions",
    ],
    pythonConceptSlugs: ["defaultdict"],
  },
  {
    id: "week-4",
    weekNumber: 4,
    theme: "Stack + Binary Search + CTE",
    pythonTopics: ["stack", "binary search"],
    leetcodeTopics: ["Stack", "BinarySearch"],
    sqlTopics: ["CteSubquery"],
    englishFocus: "edge case説明",
    problemSlugs: [
      "valid-parentheses",
      "min-stack",
      "evaluate-reverse-polish-notation",
    ],
    sqlSlugs: ["rising-temperature", "average-time-of-process-per-machine"],
    pythonConceptSlugs: ["list"],
  },
  {
    id: "week-5",
    weekNumber: 5,
    theme: "Linked List + CASE WHEN",
    pythonTopics: ["class", "linked list"],
    leetcodeTopics: ["LinkedList"],
    sqlTopics: ["CaseWhen"],
    englishFocus: "implementation plan説明",
    problemSlugs: [],
    sqlSlugs: ["employee-bonus", "not-boring-movies"],
    pythonConceptSlugs: ["class"],
  },
  {
    id: "week-6",
    weekNumber: 6,
    theme: "Trees DFS/BFS + Window関数基礎",
    pythonTopics: ["recursion", "deque"],
    leetcodeTopics: ["Trees"],
    sqlTopics: ["WindowFunctions"],
    englishFocus: "DFS/BFS説明",
    problemSlugs: [],
    sqlSlugs: ["students-and-examinations"],
    pythonConceptSlugs: ["recursion", "deque"],
  },
  {
    id: "week-7",
    weekNumber: 7,
    theme: "Graphs + ranking",
    pythonTopics: ["graph representation"],
    leetcodeTopics: ["Graphs"],
    sqlTopics: ["Ranking"],
    englishFocus: "debugging説明",
    problemSlugs: [],
    sqlSlugs: ["managers-with-at-least-5-direct-reports"],
    pythonConceptSlugs: ["defaultdict"],
  },
  {
    id: "week-8",
    weekNumber: 8,
    theme: "Heap / Intervals + rolling aggregate",
    pythonTopics: ["heapq", "sort key"],
    leetcodeTopics: ["Heap", "Intervals"],
    sqlTopics: ["RollingAggregate"],
    englishFocus: "trade-off説明",
    problemSlugs: [],
    sqlSlugs: ["confirmation-rate"],
    pythonConceptSlugs: ["heapq"],
  },
  {
    id: "week-9",
    weekNumber: 9,
    theme: "Backtracking + advanced join",
    pythonTopics: ["backtracking"],
    leetcodeTopics: ["Backtracking"],
    sqlTopics: ["AdvancedJoin"],
    englishFocus: "clarification説明",
    problemSlugs: [],
    sqlSlugs: [],
    pythonConceptSlugs: ["recursion"],
  },
  {
    id: "week-10",
    weekNumber: 10,
    theme: "Dynamic Programming + advanced aggregation",
    pythonTopics: ["DP table", "memoization"],
    leetcodeTopics: ["DP"],
    sqlTopics: ["AdvancedAggregation"],
    englishFocus: "DP説明",
    problemSlugs: [],
    sqlSlugs: [],
    pythonConceptSlugs: ["type-hints"],
  },
  {
    id: "week-11",
    weekNumber: 11,
    theme: "復習週: 弱点克服",
    pythonTopics: ["weak point review"],
    leetcodeTopics: [],
    sqlTopics: [],
    englishFocus: "mock interview",
    problemSlugs: [],
    sqlSlugs: [],
    pythonConceptSlugs: [],
  },
  {
    id: "week-12",
    weekNumber: 12,
    theme: "本番想定 / timed practice",
    pythonTopics: ["final review"],
    leetcodeTopics: [],
    sqlTopics: [],
    englishFocus: "full explanation practice",
    problemSlugs: [],
    sqlSlugs: [],
    pythonConceptSlugs: [],
  },
];
